version: "3.7"

services:

  db:
    image: postgres:12.3
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - .volumes/pgdata/:/var/lib/postgresql/data/
      - ./sql/:/home/sql/

  ymdb-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 5000:5000
    env_file: .env
    environment:
      - PYTHONPATH=/home/
    command: ["python", "app/main.py"]
    # command: ["printenv"]
    image: ymdb-app
    depends_on:
      - db
